### PR TITLE
fix(add): refer to ipfs issue #5456

### PR DESCRIPTION
**Pull request by overbool**
License: MIT
Signed-off-by: Overbool <overbool.xu@gmail.com>

Fixes: https://github.com/ipfs/go-ipfs/issues/5456

### CODE REVIEW

**Comment by overbool** [comment]
@Stebalien I'm trying to solve the https://github.com/ipfs/go-ipfs/issues/5456, but i have no idea whether my solution is correct, could you help me review my pr? Thx

**Comment by Stebalien** [comment]
I think this is the correct fix but I'd like @keks to sign off on it.

**Comment by Stebalien** [comment]
However, it needs a `go fmt`.

**Comment by overbool** [comment]
@Stebalien @keks I had fixed it

**Comment by keks** [comment]
This looks good!

@Stebalien do you think there should be a test for this edge case to prevent regressions?

**Comment by Stebalien** [comment]
@keks yes. However, I like merging bug fixes, with or without tests, as long as we leave the bug open.

**Pull request merged**
