### PR TITLE
allow stdin on Windows

### PR DESCRIPTION
**Pull request by djdv**
This may be all that has to be done in cmds for now, the rest may be in go-ipfs itself.
Ref: https://github.com/ipfs/go-ipfs/issues/4808

### CODE REVIEW

**Comment by djdv** [comment]
FWIW I plan on adding something similar to this in `go-ipfs/shareness`
```
  test_expect_success "stdin reading message shows up" '
  case $(uname) in
  MSYS*)
    test_expect_code 1 grep "ipfs: Reading from" add_help_err &&
    test_expect_code 1 grep "send Ctrl-z to stop." add_help_err
    ;;
  *)
    test_expect_code 1 grep "ipfs: Reading from" add_help_err &&
    test_expect_code 1 grep "send Ctrl-d to stop." add_help_err
    ;;
  esac
  '
```
which should address what codecov is upset over.

**Comment by Stebalien** [comment]
> This may be all that has to be done in cmds for now, the rest may be in go-ipfs itself.

Does this actually fix the issue in question or does something else need to be done to make stdin work on windows? 

Do you have any idea why this check was added? I assume there was a reason.

**Comment by djdv** [comment]
>Does this actually fix the issue in question or does something else need to be done to make stdin work on windows?

Partially, see https://github.com/ipfs/go-ipfs/issues/4808#issuecomment-372678893
stdin+stdout appear to be working as long as the daemon is running, I'll have to investigate `go-ipfs` to see if something can be done about the lock while the daemon is down. I can't see why it's not released before the next command is issued.

I'm going to bounce back and forth trying to get tests around stdio working on Windows.

>Do you have any idea why this check was added? I assume there was a reason.

It's a little unclear unfortunately.
https://github.com/ipfs/go-ipfs/issues/3266

**Comment by whyrusleeping** [comment]
@djdv any update here? Should we just merge this and push it into go-ipfs?

**Comment by Stebalien** [comment]
@whyrusleeping @djdv 

Let's merge it. I still don't know why we disabled this command on Windows in the past (and not Linux) but we might as well try it.

**Pull request merged**
